//タイトル並び替え確認ハンドル 0:昇順 1:降順
to handle sort_by_title_confirm_hdl with sort_by_title
	Global G_phone_type,today_date
	Log "タイトル並び替え確認ハンドル"
	wait 5s
	Try
		//G_phone_type 1:android 0:ios
		If G_phone_type = "1" then
			put [10,160] into TL_point
			put [0,78] into TR_point	
		Else 
			put [10,145] into TL_point
			put [0,78] into TR_point
		End if
		//並び替え順番でファイル名取得し、作成順番のファイルと比較
		Set file_name_location to EveryImageRectangle(Text:today_date)
		//1番目ファイルからファイル数ロープして、ファイル比較
		repeat with each Rectangle of file_name_location
			if repeatIndex() > 1 then
				//当ファイル名取得
				put the TopLeft of Rectangle into TopLeft_file_icon
				put the TopRight of Rectangle into TopRight_file_icon
				put TopLeft_file_icon-TL_point into TL
				put TopRight_file_icon-TR_point + RemoteScreenSize()*[0.3,0] into TR
				Put ReadText(TL,TR,DPI:"250") into found_file_name2
				//タイトルなしは空白に変換
				if found_file_name2 = "タイトルなし" then
					put "" into found_file_name2
				end if
				log found_file_name2
				
				//前ファイル名取得
				wait 3s
				Set file_name_location2 to EveryImageRectangle(Text:today_date)
				put item repeatIndex()-1 of file_name_location2 into Rectangles
				put the TopLeft of Rectangles into TopLeft_file_icon
				put the TopRight of Rectangles into TopRight_file_icon
				put TopLeft_file_icon-TL_point into TL
				put TopRight_file_icon-TR_point + RemoteScreenSize()*[0.3,0] into TR
				Put ReadText(TL,TR,DPI:"250") into found_file_name1
				//タイトルなしは空白に変換
				if found_file_name1 = "タイトルなし" then
					put "" into found_file_name1
				end if
				log found_file_name1
				If sort_by_title = 0 then
					//タイトル昇順比較
					if found_file_name2 < found_file_name1 then
						LogError "ファイル並び替え(タイトル/昇順)順番問題ある"
					end if
				Else if sort_by_title = 1
					//タイトル降順比較
					if found_file_name2 > found_file_name1 then
						LogError "ファイル並び替え(タイトル/降順)順番問題ある"
					end if
				End if
			end if
		end repeat
		
		If sort_by_title = 0 then
			Log "ファイル並び替え(タイトル/昇順)順番問題なし"
		Else if sort_by_title = 1
			Log "ファイル並び替え(タイトル/降順)順番問題なし"
		End if
		
	Catch theException
		LogError "エラーが発生しました"
	End try
	
end sort_by_title_confirm_hdl
