to handle cm_create_folder_hdl with Data_File_Excel,Text_Line,terminal_flg
	Global  folder_teminal,folder_cloud
	log "Text_Line:"&Text_Line
	//ワークブックファイルを指定
	set Variable_File to Workbook(ResourcePath(Data_File_Excel))
	//ワークブック内にある個別のワークシートを指定
	set Variable_data to Worksheet(Variable_File, "Folder_Data")
	//ワークシートの特定のセルの値を抽出(行,列)
	put Variable_data.Cell(Text_Line,1) into Title_Text
	//terminal_flgから格納する変数を確定
	if terminal_flg=1
	then 
		//端末の場合
		insert Title_Text before folder_teminal
	else
		//クラウドの場合
		insert Title_Text before folder_cloud
	end if
	log "folder_teminal"&folder_teminal
	log "folder_cloud"&folder_cloud
	Log "タイトル："&Title_Text
	wait 3
	waitfor 10s,image:"create_folder_btn"
	click image:"create_folder_btn"
	wait 2s
	set the KeyDownDelay to .5
	TypeText Title_Text
	wait 2
end cm_create_folder_hdl