(*global G_folder_name,G_file_name,terminal_flg,cloud_flg,file_content_cloud,G_file_content,file_cloud,folder_cloud
Log "**処理内容：クラウドの表示確認処理**"
wait 5s
click image:"cloud_tab"
wait 1s
waitfor 5,image:"cloud_tab/on"
////端末を選択した場合、terminal_flgが「０」、cloud_flgが「１」
put 0 into terminal_flg
put 1 into cloud_flg
put folder_cloud into G_folder_name
put file_cloud into G_file_name
put file_content_cloud into G_file_content
log "G_folder_name:"&G_folder_name
log "G_file_name:"&G_file_name
log "クラウドの表示確認済"*)