
//画面を縮小
to handle Pinch_In 
	try
		PinchIn at:[200,500],from:[600,1000],Duration:12
	catch e
		assert e contains "Pinch timed out waiting for response from server after 10 seconds"
	end try
	
end Pinch_In

//画面を拡大
to handle Pinch_Out
	try
		PinchOut at:[419,722],to:[490,1108]
	catch e
		assert e contains "Pinch timed out waiting for response from server after 10 seconds"
	end try
end Pinch_Out

//--------------------------







