params Action_Count
Global G_file_name,G_file_content,G_operate_file_name,G_operate_file_content,G_operate_folder_name
Log "**処理内容：スワイプで任意端末フォルダへ移動＆下書き手動一番上に移動**"

wait 5s
Log "変数から情報取得"
Log "ファイルList："&G_file_name
put item 2 of G_file_name into G_operate_file_name
put item 2 of G_file_content into G_operate_file_content
log "G_file_content"&G_file_content
log "G_operate_file_content"&G_operate_file_content
//移動前のフォルダ取得(ファイル戻るために)
wait 3s
Set folder_small_name_locations to EveryImageRectangle(ImageName:"small_folder_icon")
put item 2 of folder_small_name_locations into folder_small_name_location
put the TopRight of folder_small_name_location into TR_small_folder_icon
put the BottomRight of folder_small_name_location into BR_small_folder_icon
put ReadText(TR_small_folder_icon,BR_small_folder_icon*[0,1] + RemoteScreenSize()*[1,0],DPI:144) into small_folder_name
put small_folder_name into G_operate_folder_name
Log "移動前フォルダ名："&G_operate_folder_name
wait 3s
CaptureScreen {Name:"移動前フォルダ名_"&formattedTime("YYYY-MM-DD_HH_mm_ss")}

If G_operate_file_name = "" then
	put "タイトルなし" into operate_file_name
else
	put G_operate_file_name into operate_file_name
End if

Log operate_file_name&"左スワイプして、移動ボタン押下"
Try
	//スワイプ用座標取得し設定
	Waitfor 5s,Text:operate_file_name
	put FoundImageLocation()*[0,1] + RemoteScreenSize()*[0.5,0] into draglocation
	wait 2s
	
	Repeat until ImageFound(ImageName:"swipe/swipe_move_to")
		Log "スワイプ処理"
		SwipeLeft draglocation
		wait 5s
	End repeat
	
	Log "フォルダ移動ボタン押下"
	Waitfor 15s,ImageName:"swipe/swipe_move_to"
	Click FoundImageLocation()
	wait 2s
	//移動先選択画面表示確認
	Waitfor 15s,ImageName:"swipe/swipe_move_to_title"
	Log "移動先選択画面が表示"
	
	Log "フォルダへ移動"
	Try
		Click ImageName:"folder_icon_on"
		wait 1s
		Waitfor 5s,ImageName:"edit_btn"
		Log "フォルダへ移動は問題なし"
	Catch theException
		Log "フォルダへ移動は問題あり"
	End try
Catch theException
	LogError "任意フォルダへ移動失敗"
End try

Log "手動並び替えに切り替え"
Click ImageName:"sort/sort_by_update_day_desc"
wait 3s
Click ImageName:"sort/sort_modal_manual_able"
Try
	Waitfor 5s,ImageName:"manual_end_btn"
	Log "手動並び替え切り替え成功"
Catch theException
	LogError "手動並び替え切り替え失敗"
End try
wait 3s

Log "ファイル一番上へ移動"
CaptureScreen {Name:"手動並び替え確認_移動前_"&formattedTime("YYYY-MM-DD_HH_mm_ss")}
Run "10_common/manual_sort_hdl"'s manual_sort_hdl 0
CaptureScreen {Name:"手動並び替え確認_移動後_"&formattedTime("YYYY-MM-DD_HH_mm_ss")}

//完了
Click ImageName:"manual_end_btn"
wait 3s

Log "ディフォルト更新日降順に戻る"
//sort_type 0:タイトル 1:手動
Run "10_common/return_to_default_sort_by_hdl"'s return_to_default_sort_by_hdl 1
//todo 4822
//Click ImageName:"close_sort_by"

//Actionを実行する毎にカウントをアップする
Put Action_Count + 1 into Action_Count
return Action_Count

