params Action_Count
Global G_phone_type
Log "G_phone_type:"&G_phone_type
Log "**処理内容：複数件下書きのライトモード＆縦向レイアウト確認**"
wait 5s
//G_phone_type 1:android 0:ios
(*If G_phone_type = "1" then
	SetDeviceOrientation portrait
	Log "縦向確認済"
	//横向
	//SetDeviceOrientation landscapeRight
	//SetDeviceOrientation landscapeLeft
	wait 5s
	typetext homeKey
	wait 5s
	Click ImageName:"light_dark_modal_change_icon"
	Try
		Waitfor 5s,ImageName:"light_modal_confirm"
		wait 2s
		Log "ライトモード確認済"
	Catch theException
		Log "今はライトモードではないので、ライトモードに切替"
		Click ImageName:"dark_modal_confirm"
		Log "ライトモードに切替済み"
	End try
	typetext homeKey
	wait 5s
	
	Click ImageName:"open_app"
	Try
		Waitfor 5s,ImageName:"all_draft"
	Catch theException
		Log "アプリ再開く失敗"
	End try
	wait 2s
	
	Log "レイアウト確認"
	Try
		Waitfor 5s,ImageName:"draft_light_portrait_layout"
		Log "ライトモード&縦向きが問題なし"
		wait 3s
		CaptureScreen {Name:"ライトモード縦向レイアウト確認_"&formattedTime("YYYY-MM-DD_HH_mm_ss")}
	Catch theException
		LogError "ライトモード&縦向きが問題ある"
	End try
	
Else if G_phone_type = "0"
	SetDeviceOrientation portrait
	wait 5s
	Log "縦向確認済"
	
	//ライトモード切替
	//Waitfor 5s,ImageName:"light_dark_modal_change_icon"
	//Swipedown FoundImageLocation()
	Swipedown [1000,50]
	wait 5s
	Try
		Press ImageName:"ios_light_up_down_btn"
		wait 3s
		release
		waitfor 10,ImageName:"ios_light_dark_change_btn/ios_dark_change_btn"
		Log "ライトモード確認済み"
		wait 1
	Catch theException
		log "ライトモードに変更"
		waitfor 5,image:"ios_light_dark_change_btn/ios_light_change_btn"
		Click image:"ios_light_dark_change_btn/ios_light_change_btn"
		wait 1
		waitfor 5,"ios_light_dark_change_btn/ios_dark_change_btn"
	End try
	typetext homeKey
	wait 5s
	typetext homeKey
	wait 5s
	
	//レイアウト確認
	Try
		Waitfor 10s,ImageName:"draft_light_portrait_layout"
		Log "ライトモード＆縦向きレイアウトは問題なし"
		wait 3s
		CaptureScreen {Name:"ライトモード縦向レイアウト確認_"&formattedTime("YYYY-MM-DD_HH_mm_ss")}
	Catch theException
		LogError "ライトモード＆縦向きレイアウトは問題ある"
	End try	
else
	LogError "スマホシステム確認できない"
End if*)

//Actionを実行する毎にカウントをアップする
Put Action_Count + 1 into Action_Count
return Action_Count

