params Action_Count
Global sort_state,sort_state_string

Log "**処理内容：並び替えモダール表示確認**"
wait 5s
(*Try
	swipeDown
	wait 5s
	Waitfor 5s,ImageName:"sort/sort_by_update_day_desc"
	put "sort_modal_update_day_desc" into sort_state
	put "更新日降順" into sort_state_string
	Log "現在並び替え状態：更新日降順"
	Click FoundImageLocation()
	wait 1s
Catch theException
	Try
		Waitfor 5s,ImageName:"sort/sort_by_update_day_asc"
		put "sort_modal_update_day_asc" into sort_state
		put "更新日昇順" into sort_state_string
		Click FoundImageLocation()
		wait 1s
		Log "現在並び替え状態：更新日昇順"
	Catch theException
		Try
			Waitfor 5s,ImageName:"sort/sort_by_title_desc"
			put "sort_modal_title_desc" into sort_state
			put "タイトル降順" into sort_state_string
			Click FoundImageLocation()
			wait 1s
			Log "現在並び替え状態：タイトル降順"
		Catch theException
			Try
				Waitfor 5s,ImageName:"sort/sort_by_title_asc"
				put "sort_modal_title_asc" into sort_state
				put "タイトル昇順" into sort_state_string
				Click FoundImageLocation()
				wait 1s
				Log "現在並び替え状態：タイトル昇順"
			Catch theException
				LogError "現在並び替え状態は更新日降順ではありません"				
			End try
		End try
	End try
End try

Try
	Waitfor 5s,ImageName:"sort/sort_by_modal"
	Log "並び替えモダール表示成功"
	CaptureScreen {Name:"並び替えモダール表示_"&formattedTime("YYYY-MM-DD_HH_mm_ss")}
Catch theException
	LogError "並び替えモダール表示失敗"
End try*)

//Actionを実行する毎にカウントをアップする
Put Action_Count + 1 into Action_Count
return Action_Count

