Params Action_Count
Log "**処理内容：タイトル並び替え確認**"

Log "タイトル/降順並び替え確認"
(*wait 5s
Try
	//タイトル/降順に変える
	Click ImageName:"sort/sort_modal_title_btn"
	wait 1s
	//変更した並び替え状態確認：タイトル降順
	Waitfor 5s,ImageName:"sort/sort_modal_title_desc"
	Log "並び替えはタイトル降順に変えました"
	Click ImageName:"close_sort_by"
	wait 2s
	//タイトル並び替え確認ハンドル呼ぶ 1:降順
	Run "10_common/sort_by_title_confirm_hdl"'s sort_by_title_confirm_hdl 1
	wait 2s
	CaptureScreen {Name:"タイトル降順確認_"&formattedTime("YYYY-MM-DD_HH_mm_ss")}
Catch theException
	LogWarning "並び替えはタイトル降順に変えませんでした"
End try
wait 2s
Log "タイトル/昇順並び替え確認"
Try
	//並び替えモード開く
	Waitfor 5s,ImageName:"sort/sort_by_title_desc"
	Click FoundImageLocation()
	wait 2s
	Waitfor 5s,ImageName:"sort/sort_by_modal"
	//タイトル/昇順に変える
	Click ImageName:"sort/sort_modal_title_btn"
	wait 2s
	try
		//変更した並び替え状態確認：タイトル昇順
		Waitfor 5s,ImageName:"sort/sort_modal_title_asc"
		Log "並び替えはタイトル昇順に変えました"
		Click ImageName:"close_sort_by"
		wait 1s
	Catch
		Click ImageName:"sort/sort_modal_title_btn"
		wait 1s
		Waitfor 5s,ImageName:"sort/sort_modal_title_asc"
		LogError "タイトル昇順に変わらない"
		Log "強制タイトル昇順に変えます"
	end try
	
	wait 2
	//タイトル並び替え確認ハンドル呼ぶ 0:昇順
	Run "10_common/sort_by_title_confirm_hdl"'s sort_by_title_confirm_hdl 0
	CaptureScreen {Name:"タイトル昇順確認_"&formattedTime("YYYY-MM-DD_HH_mm_ss")}
Catch theException
	put "1" into skip_flg
	Click ImageName:"sort/sort_modal_update_day_btn"
	wait 1s
	LogError "並び替えはタイトル昇順変わりませんでした"
End try
wait 2s

If skip_flg <> "1" then
	//sort_type 0:タイトル 1:手動
	Log "ディフォルト並び替え戻る用共通ハンドル呼ぶ"
	Run "10_common/return_to_default_sort_by_hdl"'s return_to_default_sort_by_hdl 0	
End if

//Log "ディフォルト並び替え戻る用共通ハンドル呼ぶ"
//sort_type 0:タイトル 1:手動
//Run "10_common/return_to_default_sort_by_hdl"'s return_to_default_sort_by_hdl 0

//Actionを実行する毎にカウントをアップする*)
Put Action_Count + 1 into Action_Count
return Action_Count

