params Action_Count
Global G_file_name
Log "**処理内容：端末へ移動⇒移動先の下書き並び替え状態(更新日/降順)に応じて正しい位置へ移動されること確認**"

Log "端末へ移動"
(*
wait 5s
Try
	Click ImageName:"folder_icon_on"
	wait 1s
	Waitfor 5s,ImageName:"edit_btn"
	Log "フォルダへ移動完了"
Catch theException
	Log "フォルダへ移動は問題あり"
End try

Log "ファイルは並び替え(更新日/降順)確認"
//タイトル並び替え確認ハンドル呼ぶ 0:昇順
Run "10_common/sort_by_update_day_confirm_hdl"'s sort_by_update_day_confirm_hdl G_file_name
wait 3s
CaptureScreen {Name:"スワイプ移動更新日並び替え降順確認_"&formattedTime("YYYY-MM-DD_HH_mm_ss")}
*)

//Actionを実行する毎にカウントをアップする
Put Action_Count + 1 into Action_Count
return Action_Count

