Params Inside_folder_flg,Action_Count
Global G_operate_file_name,G_operate_folder_name

//ファイル移動後内容確認ハンドル呼ぶ
(*wait 5s
Run "10_common/after_move_text_confirm_hdl"'s after_move_text_confirm_hdl

Log "片付け処理"
//ファイル閉じる
Click ImageName:"close_create_file"
wait 5s

//ファイル戻る処理
Click ImageName:"edit_btn"
wait 5s
If G_operate_file_name = "" then
	put "タイトルなし" into operate_file_name
else
	put G_operate_file_name into operate_file_name
End if
Click Text:operate_file_name
wait 5s
Click ImageName:"move_to_btn"
wait 5s

Click Text:G_operate_folder_name
wait 5s

//Inside_folder_flg 0:フォルダ外 1:フォルダ内
//フォルダ内の場合、下書き一覧戻る必要はないので
If Inside_folder_flg <> "1" then
	Click ImageName:"folder_back_btn"
	wait 5s
	Click ImageName:"draft_tab"
	wait 3s
	Try
		Waitfor 5s,ImageName:"all_draft"
		Log "下書き一覧に戻りました"
	Catch theException
		LogError "下書き一覧に戻る失敗"
	End try
End if*)

//Actionを実行する毎にカウントをアップする
Put Action_Count + 1 into Action_Count
return Action_Count

