Params Data_File_Excel
Log "**処理内容：フォルダ作成の初回表示確認処理**"
wait 5s
//ワークブックファイルを指定
set Variable_File to Workbook(ResourcePath(Data_File_Excel))
//ワークブック内にある個別のワークシートを指定
set Variable_data to Worksheet(Variable_File, "Folder_Data")
//開始行
put Variable_data.Cell(1,3) into Start_Line
//終了行
put Variable_data.Cell(1,5) into End_Line
CaptureScreen {Name: "create_folder"&"_"&today&"_"&formattedTime("%H-%M-%S",time)}
wait 2
//フォルダ作成処理（データファイル、行、端末）
run "10_common/cm_create_folder_hdl"Data_File_Excel, random(Start_Line, End_Line),1
wait 2s
click image:"create_folder_name"//作成押下
log "フォルダ作成が正常"