(*//ファイル作成
to handle cm_create_file_hdl with Data_File_Excel,Text_Line,terminal_flg
	Global  file_terminal,file_cloud,file_content_terminal,file_content_cloud
	log "Text_Line:"&Text_Line
	//ワークブックファイルを指定
	set Variable_File to Workbook(ResourcePath(Data_File_Excel))
	//ワークブック内にある個別のワークシートを指定
	set Variable_data to Worksheet(Variable_File, "File_Data")
	//ワークシートの特定のセルの値を抽出(行,列)
	put Variable_data.Cell(Text_Line,1) into Title_Text
	put Variable_data.Cell(Text_Line,2) into Body_Text
	put Variable_data.Cell(Text_Line,3) into Emoji_Text
	if terminal_flg=1
	then 
		//端末の場合
		insert Title_Text before file_terminal
		insert Body_Text before file_content_terminal
	else
		//クラウドの場合
		insert Title_Text before file_cloud
		insert Body_Text before file_content_cloud
	end if
	Log "タイトル："&Title_Text
	waitfor 5s, image:"input_title"
	wait 1s
	click image:"input_title"
	wait 2s
	TypeText Title_Text//タイトル入力
	wait 3s
	Log "本文："&Body_Text&Emoji_Text
	waitfor 10s, image:"input_text"
	wait 1s
	click image:"input_text"
	wait 2s
	TypeText Body_Text&Emoji_Text//本文入力
	wait 3s
	CaptureScreen {Name: "create_file"&"_"&today&"_"&formattedTime("%H-%M-%S",time)}
	wait 2s
	click image:"save_file"//保存押下
	wait 2s
	//waitfor 10s,image:"save_tutorial"//保存確認
	
end cm_create_file_hdl*)