(*
//ファイル更新時間により、ファイル名list取得
function get_file_name_list_by_date_hdl with
	Global G_phone_type,today_date
	//G_phone_type 1:android 0:ios
	wait 5s
	If G_phone_type = "1" then
		put [10,145] into TL_point
		put [0,78] into TR_point
	Else 
		put [10,145] into TL_point
		put [0,78] into TR_point
	End if
	Set file_name_location to EveryImageRectangle(Text:today_date)
	repeat with each Rectangles of file_name_location
		//ファイル名取得
		put the TopLeft of Rectangles into TopLeft_file_icon
		put the TopRight of Rectangles into TopRight_file_icon
		insert ReadText(TopLeft_file_icon-TL_point,TopRight_file_icon-TR_point + RemoteScreenSize()*[0.3,0],DPI:"250") after found_file_name
		log "found_file_name_by_date"&found_file_name
	end repeat
	return found_file_name
end get_file_name_list_by_date_hdl
*)
