(*
//ファイルの元フォルダ取得ハンドル
//folder_type 0:小さいフォルダ 1:普通フォルダ
//move_type 0:複数 1:一括
to handle get_small_folder_name_hdl with move_type,folder_type
	Global origin_small_folder_name
	put "" into origin_small_folder_name
	wait 5s
	//操作するファイルのフォルダ名取得
	SwipeUp
	wait 10s
	If folder_type = "0" then
		Set folder_small_name_location to EveryImageRectangle(ImageName:"small_folder_icon")
	Else if folder_type = "1"
		Set folder_small_name_location to EveryImageRectangle(ImageName:"folder_icon")
		//一番フォルダは未分類の場合、listから未分類フォルダを削除
		put item 1 of folder_small_name_location into delete_rectangle
		put the TopRight of delete_rectangle into TopRight_folder_icon
		put the BottomRight of delete_rectangle into BottomRight_folder_icon
		Put ReadText(TopRight_folder_icon,BottomRight_folder_icon*[0,1] + RemoteScreenSize()*[1,0]) into found_folder_name
		If found_folder_name = "未分類" then
			delete item 1 of folder_name_location
		End if
	End if
	wait 3s
	Log "folder_small_name_location"&folder_small_name_location
	//ファイル数ロープして、フォルダ名取得
	repeat with each Rectangle of folder_small_name_location
		//複数ファイルの場合、2ファイルまでループする
		If move_type = "0" then
			If repeatindex() > 2 then Exit repeat
		End if
		wait 3s
		//画面表示フォルダ名取得
		put the TopRight of Rectangle into TR_small_folder_icon
		put the BottomRight of Rectangle into BR_small_folder_icon
		Put ReadText(TR_small_folder_icon,BR_small_folder_icon*[0,1] + RemoteScreenSize()*[1,0]) into small_folder_name
		//フォルダ名保存
		If small_folder_name = "未分類" then
			Next repeat
		End if
		insert small_folder_name after origin_small_folder_name
	end repeat
	Log "フォルダ名："&origin_small_folder_name
end get_small_folder_name_hdl
*)
