(*
//ディフォルト並び替え順「更新日降順」に戻る
//sort_type 0:タイトル 1:手動
to handle return_to_default_sort_by_hdl with sort_type
	Log "ディフォルト並び替え順「更新日降順」に戻る"
	Try
		wait 5s
		//並び替えモード開く
		If sort_type = "0" then
			Waitfor 5s,ImageName:"sort/sort_by_title_asc"
		Else if sort_type = "1"
			Waitfor 5s,ImageName:"sort/sort_by_manual"
		End if
		Click FoundImageLocation()
		wait 3s
		Waitfor 5s,ImageName:"sort/sort_by_modal"
		//更新日/降順に変える
		Click ImageName:"sort/sort_modal_update_day_btn"
		wait 1s
		repeat until imagefound(image:"sort/sort_modal_update_day_desc")
			if the repeatindex = 10 then throw "Image not found", "Image not found while scrolling"&&Direction&priod
			Click ImageName:"sort/sort_modal_update_day_btn"
			wait 5s
		end repeat
		//変更した並び替え状態確認：更新日降順
		Waitfor 5s,ImageName:"sort/sort_modal_update_day_desc"
		wait 3s
		//手動の場合、並び替えモーダルを閉じる
		If sort_type = "1" then
			Click ImageName:"close_sort_by"
		End if
		Log "並び替えは更新日降順に戻りました"
		wait 5s
	Catch theException
		//手動の場合、並び替えモーダルを閉じる
		If sort_type = "1" then
			Click ImageName:"sort/sort_modal_update_day_btn"
			wait 1s
			repeat until imagefound(image:"sort/sort_modal_update_day_desc")
				if the repeatindex = 10 then throw "Image not found", "Image not found while scrolling"&&Direction&priod
				Click ImageName:"sort/sort_modal_update_day_btn"
				wait 5s
			end repeat
			//変更した並び替え状態確認：更新日降順
			Waitfor 5s,ImageName:"sort/sort_modal_update_day_desc"
			wait 3s
			Click ImageName:"close_sort_by"
		else
			Click ImageName:"sort/sort_modal_update_day_btn"
		End if
		LogError "並び替えは更新日降順に戻りませんでした"
	End try
end return_to_default_sort_by_hdl
*)
