(*
//移動したファイル元に戻るハンドル
//P1:ファイル名list、P2:フォルダ名list,P3:移動したフォルダ名
//folder_type 0:端末から 1:クラウドから
to handle return_file_to_original_folder_hdl with folder_type
	Global origin_file_name,origin_small_folder_name,move_to_folder_nm
	log origin_small_folder_name
	wait 5s
	repeat with each file_name of origin_file_name
		//移動前フォルダ取得
		put item repeatindex() of origin_small_folder_name into folder_name
		//移動前と移動後フォルダが同じの場合スキップ
		If move_to_folder_nm = folder_name then
			Log folder_name&"移動前後フォルダが同じので、スキップ"
			next repeat
		End if
		
		Click ImageName:"edit_btn"
		wait 3s
		Click Text:file_name
		wait 3s
		Click ImageName:"move_to_btn"
		wait 3s
		//クラウドから端末へ戻るの場合、端末タブを押下
		If folder_type = "1" then
			Click ImageName:"terminal_tab"
			wait 3s
		End if
		Click Text:folder_name
		wait 3s
		Click ImageName:"folder_back_btn"
		wait 3s
		//クラウドから端末へ戻るの場合、クラウドタブを押下
		If folder_type = "1" then
			Click ImageName:"cloud_tab"
			wait 3s
		End if
		Click Text:move_to_folder_nm
		wait 3s
	end repeat 
	wait 5s
	Click ImageName:"folder_back_btn"
	wait 3s
	//クラウドから端末へ戻るの場合、クラウドタブを押下
	If folder_type = "1" then
		Click ImageName:"terminal_tab"
		wait 3s
	End if
end return_file_to_original_folder_hdl
*)
