to handle try_catch_1
	try
		waitfor 10s,image:"Chrome"
		result_hdl.Result_Pass "try_catchテストでtry中の処理を実行するパターン確認","Android"
	catch
		result_hdl.Result_Fail "try_catchテストでtry中の処理を実行するパターン確認","Android"
	end try
end try_catch_1

to handle try_catch_2
	try
		waitfor 5s,text:"あいうえお"
		result_hdl.Result_Fail "try_catchテストでcatch中の処理を実行するパターン確認","Android"
	catch
		log "pass"
		result_hdl.Result_Pass "try_catchテストでcatch中の処理を実行するパターン確認","Android"
	end try
end try_catch_2