to handle cm_login_hdl with Text_Line,first_time_flg,Data_File_Excel
	//ワークブックファイルを指定
	set Variable_File to Workbook(ResourcePath(Data_File_Excel))
	//ワークブック内にある個別のワークシートを指定
	set Variable_data to Worksheet(Variable_File, "Account")
	//ワークシートの特定のセルの値を抽出(行,列)
	put Variable_data.Cell(Text_Line,2) into ID
	put Variable_data.Cell(Text_Line,3) into password
	Log "ID："&ID
	Log "PW："&password
	
	wait 5s
	//初回起動フラグが0の場合（初回起動以外の場合）
	if first_time_flg=0 then
		//初回起動以外の場合、ログイン状態確認
		//ログイン済みの場合一度ログアウトを行います。s
		Run "03_login_logout/04_sc_logout"
		wait 2s
		click image:"login_state_btn"
		wait 2s
	end if
	
	//初回、メニュー　共通ログイン処理
	repeat 5 times
		try
			waitfor 10s,image:"login_btn"
			wait 1s
			click image:"login_btn"
			wait 5s
			Exit repeat
		catch
			SwipeUp 
			wait 3s
		end try
	end repeat
	//ID・PWの入力
	CaptureScreen {Name: "ログイン前"&""&today&""&formattedTime("%H-%M-%S",time)}
	waitfor 20s,image:"gooID_insert"
	wait 5s
	click image:"gooID_insert"
	wait 3s
	TypeText ID//ID入力
	wait 5s
	click image:"pw_insert"
	wait 3s
	TypeText password//パスワード入力
	wait 5s
	click image:"login_btn_byid"
	wait 1s
	
	try
		waitfor 10s,image:"no_save_btn"
		click image:"no_save_btn"
	end try
	//dアカウント連携（連携しない）
	waitfor 10,image:"no_d_account_login"
	wait 1s
	click image:"no_d_account_login"
	wait 2s
	CaptureScreen {Name: "ログイン後"&""&today&""&formattedTime("%H-%M-%S",time)}
	//登録端末がある場合、登録済みの端末を解除し、新規で登録を行う。
	Try
		waitfor 10s,image:"terminal_setting"
		Try
			SwipeUp 
			wait 5s
			waitfor 10s,image:"select_terminal"
			wait 1s
			click image:"select_terminal"
			wait 2s
			waitfor 10s,image:"un_segister"
			wait 1s
			click image:"un_segister"
			wait 2s
		End try
		waitfor 10s,image:"segister"
		click image:"segister"
		wait 1s
	End try
	//キャンペーンのポップアップが出た場合、閉じる。
	wait 2s
	try
		waitfor 10s,image:"close_campaign_popup"
		click image:"close_campaign_popup"
		wait 2s
		try
			waitfor 5s,image:"close_campaign_popup"
			click image:"close_campaign_popup"
		end try
	end try
	wait 2s
end cm_login_hdl
