global terminal_flg,cloud_flg,folder_teminal,folder_cloud,folder_select,file_terminal,file_cloud,G_file_name,G_file_content
Log "**処理内容：フォルダ選択処理**"
wait 5s
click "folder_tab"
wait 2
put 1 into folder_select
//端末の場合
if terminal_flg=1
then
	//folder_teminalリストから1番目の値を取得
	put item 1 of folder_teminal into Title_Text
	delete item 1 of file_terminal
	put file_terminal into G_file_name
	delete item 1 of G_file_content
	log "G_file_content"&G_file_content
	log "タイトル:"&Title_Text
	log "file_terminal:"&file_terminal
else if terminal_flg=0 //クラウドの場合
	//folder_cloudリストから1番目の値を取得
	put item 1 of folder_cloud into Title_Text
	delete item 1 of file_cloud
	put file_cloud into G_file_name
	delete item 1 of G_file_content
	log "G_file_content"&G_file_content
	log "タイトル:"&Title_Text
	log "file_cloud:"&file_cloud
end if
//特定のフォルダ名をクリック
click text:Title_Text
Log "特定のファイル選択問題なし"

