global G_folder_name,G_file_name,terminal_flg,cloud_flg,file_content_terminal,G_file_content,file_terminal,folder_teminal
Log "**処理内容：端末の表示確認処理**"
wait 5s
click image:"terminal_tab"
wait 1s
waitfor 5,image:"terminal_tab/on"
//端末を選択した場合、terminal_flgが「１」、cloud_flgが「０」
put 1 into terminal_flg
put 0 into cloud_flg
put folder_teminal into G_folder_name
put file_terminal into G_file_name
put file_content_terminal into G_file_content
log "G_folder_name:"&G_folder_name
log "G_file_name:"&G_file_name
log "端末の表示確認済"