Params Inside_folder_flg,Action_Count
Global G_file_name,G_folder_name,origin_file_name,origin_small_folder_name,move_to_folder_nm
Log "**処理内容：複数ファイルクラウドへ移動確認**"
wait 5s
Log "複数ファイル移動"
Run "10_common/move_to_other_folder_hdl"'s move_to_other_folder_hdl 0,1
wait 5s
Log "ファイル戻る"
Run "10_common/return_file_to_original_folder_hdl"'s return_file_to_original_folder_hdl 1
wait 5s
//Inside_folder_flg 0:フォルダ外 1:フォルダ内
//フォルダ内の場合、下書き一覧戻る必要はないので
If Inside_folder_flg <> "1" then
	Click ImageName:"draft_tab"
	wait 3s
	Try
		Waitfor 5s,ImageName:"all_draft"
		Log "下書き一覧に戻りました"
	Catch theException
		LogError "下書き一覧に戻る失敗"
	End try
else
	put item 1 of origin_small_folder_name into folder_name
	Click Text:folder_name
End if

//Actionを実行する毎にカウントをアップする
Put Action_Count + 1 into Action_Count
return Action_Count

