params Action_Count
Log "**処理内容：ログイン(課金)の場合手動並び替えモーダル＆フォルダ移動確認**"
wait 5s
Try
	Click ImageName:"sort/sort_by_create_date_desc"
	wait 3s
	Click ImageName:"sort/sort_modal_manual_able"
	wait 3s
	Waitfor 5s,ImageName:"sort/sort_modal_manual_confirm"
	Log "手動並び替えが移行しました"
	CaptureScreen {Name:"手動モーダル表示_"&formattedTime("YYYY-MM-DD_HH_mm_ss")}
	Catch theException
	LogError "手動並び替えが移行しません"
End try

Log "別画面遷移不可確認"
Try
	Waitfor 5s,ImageName:"draft_tab"
Catch theException
	Try
		Waitfor 5s,ImageName:"folder_tab"
	Catch theException
		Try
			Waitfor 5s,ImageName:"dictionary_tab"
		Catch theException
			Try
				Waitfor 5s,ImageName:"menu_tab"
			Catch theException
				Try
					Waitfor 5s,ImageName:"edit_btn"
				Catch theException
					Try
						Log "ドラック＆ドロップ処理"		
						CaptureScreen {Name:"フォルダ手動ドラック＆ドロップ確認_移動前_"&formattedTime("YYYY-MM-DD_HH_mm_ss")}
						wait 3s
						Run "10_common/manual_sort_hdl"'s manual_sort_hdl 1
						wait 3s
						CaptureScreen {Name:"フォルダ手動ドラック＆ドロップ確認_移動後_"&formattedTime("YYYY-MM-DD_HH_mm_ss")}
						
						Log "手動モード完了後、並び替え準確認"
						//手動並び替え完了前ファイル名保存 変数設定 origin_small_folder_name
						Run "10_common/get_small_folder_name_hdl"'s get_small_folder_name_hdl 1,1
						wait 3s
						put origin_small_folder_name into bf_file_name_list
						//完了ボタン押下
						Click ImageName:"manual_end_btn"
						wait 3s
						//手動モード完了、元の状態に戻ることを確認
						Try
							Waitfor 5s,ImageName:"folder_tab"
							Log "手動モード完了、元の状態に戻りました"
						Catch theException
							LogError "手動モード完了、元の状態に戻らない"
						End try
						
						//手動並び替え完了後ファイル名保存
						Run "10_common/get_small_folder_name_hdl"'s get_small_folder_name_hdl 1,1
						wait 3s
						put origin_small_folder_name into af_file_name_list
						wait 3s
						//並び替え順番確認
						If bf_file_name_list <> af_file_name_list then
							LogError "フォルダ手動並び替え順番が問題あり"
						End if
						Log "フォルダ手動並び替え順番が問題なし"
						
						Log "ディフォルト作成日降順に戻る"
						Try
							Click ImageName:"sort/sort_by_manual"
							wait 3s
							Click Text:"作成日"
							wait 3s
							Click ImageName:"close_sort_by"
							Waitfor 5s,ImageName:"folder_confirm"
							Log "フォルダ一覧戻りました"
							
							//Actionを実行する毎にカウントをアップする
							Put Action_Count + 1 into Action_Count
							return Action_Count
							
						Catch theException
							LogError "フォルダ一覧戻る失敗"
						End try
					Catch theException
						LogError "別画面に遷移できます"
					End try
				End try
			End try
		End try
	End try
End try
//上記画像どちらか一つ見つける場合は画面遷移できます
LogError "別画面に遷移できます"

