params Login_NoPay_Type_Run,Login_Pay_Type_Run,Data_File_Excel
global folder_teminal,folder_cloud
Log "**処理内容：文書作成_フォルダ作成処理**"
wait 5s
//ワークブックファイルを指定
set Variable_File to Workbook(ResourcePath(Data_File_Excel))
//ワークブック内にある個別のワークシートを指定
set Variable_data to Worksheet(Variable_File, "Folder_Data")
//ワークシートの特定のセルの値を抽出(行,列)
//連番のリストを作る
put Variable_data.Cell(1,3) into Start_Line
put Variable_data.Cell(1,5) into End_Line
put Variable_data.Cell(1,7) into folder_number
put Start_Line.. End_Line into NumberList 
put "" into folder_teminal
put "" into folder_cloud
log "NumberList:"&NumberList
//リストをシャッフル
put NumberList shuffled into shuffledList
log "端末でフォルダ作成"
waitfor 10s,image:"folder_tab"
click image:"folder_tab"
wait 2s
waitfor 10s,image:"terminal_tab"
click image:"terminal_tab"
wait 2s
waitfor 10s,image:"terminal_tab/on"
wait 1s
//リスト要素を消しながらループ
repeat folder_number
	pull shuffledList into Text_Line
	//ファイル作成処理（データファイル名、行、端末）
	run "10_common/cm_create_folder_hdl"Data_File_Excel, Text_Line,1
	wait 3s
	waitfor 10s,image:"create_folder_name"
	click image:"create_folder_name"//作成押下
	wait 3s
	try
		waitfor 5s,text:"フォルダ名が重複しています"
		wait 1s
		click image:"cancel_btn"
		wait 1s
		LogError "フォルダ名が重複しています"
	end try
	wait 2
end repeat
wait 2
//ログイン済の場合、ログインフラグが「1」
if Login_NoPay_Type_Run=1
then 
	put 1 into login_flg
else if Login_Pay_Type_Run=1
then
	put 1 into login_flg
end if
log "ログインフラグ:"&login_flg
if login_flg=1
//ログインフラグが「1」の場合
then	
	log "クラウドでフォルダ作成"
	click image:"cloud_tab"
	wait 2s
	waitfor 5s,image:"cloud_tab/on"
	wait 2s
	//リスト要素を消しながらループ
	repeat folder_number
		pull shuffledList into Text_Line
		//ファイル作成処理（データファイル名、行、クラウド）
		run "10_common/cm_create_folder_hdl" Data_File_Excel,Text_Line,0
		wait 2s
		waitfor 10s,image:"create_folder_name"
		click image:"create_folder_name"//作成押下
		wait 3s
		try
			waitfor 5s,text:"フォルダ名が重複しています"
			wait 3s
			click image:"cancel_btn"
			wait 3s
			LogError "フォルダ名が重複しています"
		end try
		wait 3
	end repeat
end if
wait 2s
waitfor 10s,image:"folder_tab"
click image:"folder_tab"

