global G_phone_type
Log "**処理内容：開始状態の確認**"
//アプリアイコンの表示確認
try
	wait 5s
	//端末判断
	Try
		waitfor 5s,"open_app/open_app_android"
		put 1 into G_phone_type
		Log "アプリアイコン(Android)確認"
	Catch Exception
		waitfor 5s,"open_app/open_app_ios"
		put 0 into G_phone_type
		Log "アプリアイコン(iOS)確認"
	End try
	
catch
	try
		PressHomeButton
		wait 2s
		try
			waitfor 3s,"open_app"
		catch
			SwipeLeft
		end try
		wait 1
		run "10_common/cm_kill_app"
		wait 5s
	end try
	try
		Run "02_first_open/02_sc_uninstall"
		wait 5s
	end try
	try
		Run "02_first_open/01_sc_install"
		wait 5s
	end try
	set myAppList to AppList(Full)
	try
		Run "02_first_open/03_sc_first_open"
		wait 2s
		click image:"no_login_btn"
		wait 2s
	end try
	//ポップアップが表示された場合、ポップアップを閉じる
	try
		waitfor 10s,image:"close_campaign_popup"
		click image:"close_campaign_popup"
		wait 2s
		try
			waitfor 5s,image:"close_campaign_popup"
			click image:"close_campaign_popup"
		end try
	end try
	wait 1s
	run "10_common/cm_kill_app"
end try
Log "G_phone_type:"&G_phone_type
wait 5s

Try
	//端末判断
	waitfor 10s,"open_app/open_app_android"
	put 1 into G_phone_type
	Log "アプリアイコン(Android)確認"
Catch Exception
	waitfor 10s,"open_app/open_app_ios"
	put 0 into G_phone_type
	Log "アプリアイコン(iOS)確認"
End try
Log "G_phone_type:"&G_phone_type

