Log "**処理内容：アプリ起動**"
waitfor 10s,Image:"open_app"
click Image:"open_app"
wait 2
//起動時に下書きの端末タブに移動
Try
	waitfor 10s,image:"draft_tab"
	wait 1s
	click image:"draft_tab"
	try
		waitfor 5s,image:"terminal_tab/off"
		wait 1s
		click image:"terminal_tab"
		wait 2s
	end try
	Log "アプリの起動が問題なし"
Catch theException
	LogError "アプリの起動が問題あり"
End try
try
	waitfor 5s,"information_confirm"//インフォメーションの表示確認
	click "close_information"//インフォメーションを閉じる
	wait 2s
end try
wait 2s