(*
Log "**処理内容：スワイプでファイル削除**"
wait 3

Try
	waitfor 5,"draft_tab/on"
Catch theException
	click image:"draft_tab"
	wait 1s
	waitfor 5,"draft_tab/on"	
End try
try
	waitfor 5s,image:"cloud_message"
	click image:"cloud_message"
	wait 2s
end try
SwipeUp 
wait 10s
Set delete_file_before to EveryImageRectangle(ImageName:"file_select")
//スワイプ用座標取得し設定
Waitfor 5s,image:"file_select"
put FoundImageLocation()*[0,1] + RemoteScreenSize()*[0.5,0] into draglocation
wait 2s
//スワイプ処理
Repeat until ImageFound(ImageName:"swipe_delete_btn")
	if the repeatindex = 10 then throw "Image not found", "Image not found while scrolling"&&Direction&priod
	click image:"draft_tab"
	Log "スワイプ処理"
	SwipeLeft draglocation
	wait 5s
End repeat
CaptureScreen {Name:"スワイプファイル削除_"&formattedTime("YYYY-MM-DD_HH_mm_ss")}

//SwipeLeft draglocation
waitfor 10,"swipe_delete_btn"
//削除処理
click "swipe_delete_btn"
wait 5s
Set delete_file_after to EveryImageRectangle(ImageName:"file_select")
//削除処理実行前後の数を比較
if delete_file_before=delete_file_after
	LogError "ファイル削除異常"
else
	LogSuccess "ファイルが削除されました"
end if
*)
