(*
global folder_select
Log "**処理内容：複数ファイル削除**"
wait 5s
Set delete_file_before to EveryImageRectangle(ImageName:"file_select")
click image:"edit_btn"
repeat 2
	waitfor 5s, image:"file_select_btn"
	wait 1s
	click image:"file_select_btn"
	wait 1s
end repeat
CaptureScreen {Name:"編集複数ファイル削除_"&formattedTime("YYYY-MM-DD_HH_mm_ss")}

click image:"delete_btn"
wait 5s
Set delete_file_after to EveryImageRectangle(ImageName:"file_select")
//削除処理実行前後の数を比較
if delete_file_before=delete_file_after
	LogError "ファイル削除異常"
else
	LogSuccess "ファイルが削除されました"
end if
wait 3s
log "folder_select:"&folder_select
if folder_select = 1 then
	//前の画面に戻す
	click image:"folder_tab"
	wait 10s
	Repeat while ImageFound(image:"create_file")
		if the repeatindex = 10 then throw "Image not found", "Image not found while scrolling"&&Direction&priod
		//click image:"folder_tab"
		//wait 2s
		click image:"back_btn"
		wait 5s
	End repeat
	Log "フォルダに戻る"
	put 0 into folder_select
	log "folder_select:"&folder_select
end if

*)
