Params Inside_folder_flg,Action_Count
Global G_file_name,G_folder_name,origin_file_name,origin_small_folder_name,move_to_folder_nm,folder_select
Log "**処理内容：複数ファイル端末へ移動⇒更新日降順で並び替え確認**"
wait 5s
Log "複数ファイル移動"
Run "10_common/move_to_other_folder_hdl"'s move_to_other_folder_hdl 0,0
wait 5s
Log "ファイルは並び替え(更新日/降順)確認"
//更新日降順並び替え確認ハンドル呼ぶ
Run "10_common/sort_by_update_day_confirm_hdl"'s sort_by_update_day_confirm_hdl G_file_name
wait 5s
CaptureScreen {Name:"複数ファイル移動後更新日降順確認_"&formattedTime("YYYY-MM-DD_HH_mm_ss")}
Log "ファイル戻る"
Run "10_common/return_file_to_original_folder_hdl"'s return_file_to_original_folder_hdl 0
wait 5s
//Inside_folder_flg 0:フォルダ外 1:フォルダ内
//フォルダ内の場合、下書き一覧戻る必要はないので
If Inside_folder_flg <> "1" then
	Click ImageName:"draft_tab"
	wait 2s
	Try
		Waitfor 5s,ImageName:"all_draft"
		Log "下書き一覧に戻りました"
	Catch theException
		LogError "下書き一覧に戻る失敗"
	End try
else
	put item 1 of origin_small_folder_name into folder_name
	Click Text:folder_name
End if

//Actionを実行する毎にカウントをアップする
Put Action_Count + 1 into Action_Count
return Action_Count

