(*
params First_Time_Open,Data_File_Excel
global G_phone_type
Log "**処理内容：課金アカウントでログインする処理**"
//Excel行数から課金ログインアカウント情報選択
//4行目がAndroid,5行目がiOS
wait 3s
if First_Time_Open = 0 then
	waitfor 10s,image:"menu_tab"
	click image:"menu_tab"
	wait 2s
	//初回起動以外の場合、ログイン状態確認
	//ログイン済みの場合一度ログアウトを行います。s
	Run "03_login_logout/04_sc_logout"
	wait 2s
end if
log "G_phone_type:"&G_phone_type
//端末から使用するアカウントを判断
if G_phone_type = 1 then
	//androidの場合、データファイルの2行目を指定する
	put 4 into Text_Line
else if G_phone_type = 0 then
	//iosの場合、データファイルの2行目を指定する
	Put 5 into Text_Line
end if
Log "Text_Line"&Text_Line

//ログイン処理(アカウントに該当する行、初回起動フラグ、データファイル名)
run "10_common/cm_login_hdl" Text_Line,First_Time_Open,Data_File_Excel
wait 2s
waitfor 10s,image:"menu_tab"
click image:"menu_tab"
wait 2s
waitfor 5s,image:"logout_btn"
log "正常に課金アカウントにログイン"
*)
