(*Log "**処理内容：アプリインストール**"

waitfor 10s, image:"app_store"//ストアアイコンの検索
click image:"app_store" //ストアアイコンの選択
log "アプリストア起動"
//アプリ検索を行う

try
	//検索タブを選択
	waitfor 5s,"search_tab"
	click image:"search_tab"
	wait 1
end try
waitfor 5s,image:"search_app"
click image:"search_app"
wait 1s
TypeText "idraft by goo",return
wait 5s
waitfor 10s,image:"install_app"
log "対象アプリを発見"

//対象のアプリを選択/インストール処理
click image:"install_app"
wait 1
waitfor 5s,image:"install_btn"
click image:"install_btn"
wait 3s
waitfor 180s,image:"app_open" //インストールを待機
wait 1s
set myAppList to AppList(Full)
Try
	waitfor 10s,image:"app_open/app_open_android"
	KillApp "com.android.vending"//playストアを閉じる
	
catch
	waitfor 2s,image:"app_open/app_open_ios"
	KillApp "App Store"//app storeを閉じる
	
end try


//コマンドによるパッケージファイルのインストール
//あらかじめSuiteのResourceフォルダへパッケージファイルを格納しておく
try
	//Androidの場合
	//waitfor 10,image:"app_store/app_store_android" //Playストアアイコンからandroidと判断
	//InstallApp ResourcePath("~.apk") //格納済みのパッケージファイルからアプリのインストールを実施
	
catch
	//iOSの場合
	//waitfor 10,image:"app_store/app_store_ios" //app StoreアイコンからiOSと判断
	//InstallApp ResourcePath("~.ipa") //格納済みのパッケージファイルからアプリのインストールを実施
	
end try

//インストール完了確認
Try
	waitfor 30,image:"open_app" //ホーム画面にアプリアイコンが表示されるか確認
	LogSuccess "インストール成功"
catch
	LogError "インストール失敗"
end try*)