wait 3
//connectコマンドで端末と接続
connect_hdl.Connect_Sut "Windows3(RDP)"
wait 5
result_hdl.JudgementByImage "Chrome",5,"WebConnectコマンドでSUTに接続すること確認","PC"
wait 2

//excelファイル操作・csvファイル操作
excel_file_hdl.CSV_file
excel_file_hdl.Excel_file

//if then elseコマンド
run if_then_else_hdl.if_then_else_1
run if_then_else_hdl.if_then_else_2

//repeat系
repeat_hdl.repeat_Forever
repeat_hdl.repeat_time_or_For_Duration
repeat_hdl.Repeat_Until_Condition
repeat_hdl.repeat_while
repeat_hdl.repeat_with
repeat_hdl.repeat_with_each
repeat_hdl.repeat_at_least_once_until

//addコマンド
add_hdl.add

//replaceコマンド
replace_hdl.replace

//deleteコマンド
delete_hdl.delete

//runコマンド
try
	run run_hdl.run_test
catch
	result_hdl.Result_Fail "Runコマンドで指定ハンドラーを実行","PC"
end try
//try...catch...end try コマンド
run try_catch_hdl.try_catch_1
run try_catch_hdl.try_catch_2

//RunWithNewResultsコマンド
RunWithNewResults_hdl.Run_With_New_Results

wait 2
//ImageFoundでブラウザのアイコンを探す
try
	imagefound_hdl.ImageFound_Image "Chrome"
end try
result_hdl.JudgementByImage "Chrome",10,"ImageFoundコマンドで指定画像を検知する","PC"
wait 3
//文字をダブルクリックする
try
	waitfor 10s,text:"Google Chrome"
	click_hdl.DoubleClick_Text "Google Chrome"
	wait 2s
end try
result_hdl.JudgementByImage "chrome_home_page",10,"DoubleClickコマンドでOCR認識で指定文字をダブルクリックする","PC"
//画像をクリックする
try
	click_hdl.Click_Image "close_btn"
	wait 2s
	waitfor 10s,image:"Chrome"
	result_hdl.Result_Pass "Clickコマンドで指定画像をクリックする","PC"
catch
	result_hdl.Result_Fail "Clickコマンドで指定画像をクリックする","PC"
end try
//画像をダブルクリックする
try
	waitfor 10s,image:"Chrome"
	click_hdl.DoubleClick_Image "Chrome"
	wait 2s
	result_hdl.JudgementByImage "chrome_home_page",10,"DoubleClickコマンドで指定画像をダブルクリックする","PC"
end try
//文字をクリックする
waitfor 10s,text:"画像"
click_hdl.Click_Text "画像"
wait 2s
result_hdl.JudgementByImage "search_image",10,"Clickコマンドで指定文字をクリックする","PC"
try
	put "test" into HouseNumber
	setremoteclipboard HouseNumber
	wait 2s
	TypeText ControlKey,"v"
	wait 2s
	waitfor 10s,text:HouseNumber
	result_hdl.Result_Pass "SetRemoteClipboardコマンドでコピーしたテキストを貼り付け","PC"
	click image:"input_box_clean"
catch
	result_hdl.Result_Fail "SetRemoteClipboardコマンドでコピーしたテキストを貼り付け","PC"
end try
wait 5s
//typetextで指定テキスト入力
try
	put "123abcあいうえお野村" into text
	typetext_hdl.Type_Text  text
	wait 1
	imagefound_hdl.ImageFound_Text text
	result_hdl.JudgementByText text,5,"TypeTextコマンドで検知するキストを入力する操作とImagefoundコマンドで入力したテキストを検知する","PC"
	wait 2s
	waitfor 10s,image:"close_page_btn"
	click image:"close_page_btn"
	wait 1
end try
//waitfor text
wait_hdl.WaitFor_Text "Google Chrome",10s
wait 2s
//waitfor image
wait_hdl.WaitFor_Image "Chrome",10s,
wait 2s
//wait while
wait_hdl.Wait_While
wait 2s
//wait until
wait_hdl.wait_until
wait 2s
//waitforallで、画像と文字を探す
wait_hdl.Wait_ForAll 10,"Chrome","Google Chrome"
wait 2s
//wait time
wait_hdl.WaitTime
wait 2s
//moveto [0,0]、MouseLocation()で移動したかどうかを判断
set MouseLocation_Before to MouseLocation()
log "MouseLocation_Before"&MouseLocation_Before

moveto_hdl.Moveto_Coordinate [0,0]
set MouseLocation_After to MouseLocation()
log "MouseLocation_After"&MouseLocation_After

If MouseLocation_After is [0,0] then
	result_hdl.Result_Pass "movetoコマンドで指定の場所に移動する","PC"
Else
	result_hdl.Result_Fail "movetoコマンドで指定の場所に移動する","PC"
End if
wait 2

//範囲を指定し、文字を読み取る
//log ReadText("rect_left", "rect_right.")
readtext_hdl.ReadText_ByImage "rect_left", "rect_right"
set TextToRead to the result 
log "TextToRead: "&TextToRead
set the SearchRectangle to["rect_left", "rect_right"]
result_hdl.JudgementByText TextToRead,5,"ReadTextコマンドで指定範囲内の文字を読み取る","PC"
set the SearchRectangle to[]
wait 2
DoubleClick "Chrome"
wait 2s
waitfor 10s,image:"chrome_home_page"
click image:"chrome_home_page"
put "https://docs.eggplantsoftware.com" into URL_access
//URLの入力ボックスにtypetextでURLを入力する
typetext_hdl.Type_Text URL_access
wait 2s
TypeText returnKey
waitfor 10s,text:"Eggplant Functional"
click text:"Eggplant Functional"
waitfor 10s,image:"eggplant_icon"
//scroll
scroll_hdl.ScrollWheel_Down
wait 5s
scroll_hdl.ScrollWheel_Up
(*//画面回転
rotate_hdl.rotate*)
//DragDropで、テキストを選択する
try
	Drag "drag_drop/drag_drop_left.png" //Begins the drag 70% across and 50% down the SUT screen.
	Drop "drag_drop/drag_drop_right" 
	wait 2
	try
		waitfor 10s, image:"drag_drop/drag_drop"
		result_hdl.Result_Pass "Dargコマンドでカーソルを指定位置に移動してマウスダウンアクション実行、Dropコマンドでカーソルを新しい位置に移動してマウスダウンアクションを放す","PC"
		click
		catch
		result_hdl.Result_Fail "Dargコマンドでカーソルを指定位置に移動してマウスダウンアクション実行、Dropコマンドでカーソルを新しい位置に移動してマウスダウンアクションを放す","PC"
	end try
	wait 2
end try
//トリプルクリック
try
	click_hdl.TripleClick_image "drag_drop/drag_drop_left.png"
	waitfor 10s, image:"drag_drop/drag_drop"
	result_hdl.Result_Pass "TripleClickハンドラーで指定画像を三回クリック実行する","PC"
	wait 2s
	click image:"drag_drop/drag_drop_left.png"
catch
	result_hdl.Result_Fail "TripleClickハンドラーで指定画像を三回クリック実行する","PC"
end try
//MouseButtonDown_Up
MouseButtonDown 3//Holds down the mouse right click on most mice
wait 1
MouseButtonUp 3
try
	waitfor 10s,image:"moubutton_3"
	result_hdl.Result_Pass "MouseButtonUpコマンドコマンドでパラメータで示されたマウスボタンを押す、MouseButtonUpコマンドで放す","PC"
	click image:"moubutton_3"
	
catch
	result_hdl.Result_Fail "MouseButtonUpコマンドコマンドでパラメータで示されたマウスボタンを押す、MouseButtonUpコマンドで放す"
end try
wait 2s
//keyDown_Up
KeyDown ControlKey, F4
KeyUp ControlKey, F4
wait 5s
try
	waitfor 10s,image:"Chrome"
	result_hdl.Result_Pass "KeyUpコマンドで指定されたキーを押し続けて、KeyDownコマンドでキーを解放する","PC"
catch
	result_hdl.Result_Fail "KeyUpコマンドで指定されたキーを押し続けて、KeyDownコマンドでキーを解放する","PC"
end try

//ブラウザを初期化して閉じて、各logを出力
Try
	try
		waitfor 10s,image:"close_page_btn"
		click image:"close_page_btn"
	end try
	wait 5
	log_hdl.Log_Msg "Log_ブラウザを閉じました"
	log_hdl.Log_Success "LogSuccess_ブラウザを閉じました"
	log_hdl.Log_Warning "LogWarning_ブラウザを閉じました"
	result_hdl.Result_Pass "Log LogSuccess LogWarningコマンドテスト","PC"
Catch theException
	result_hdl.Result_Fail "Log LogSuccess LogWarningコマンドテスト","PC"
End try
wait 2
WebDriver_hdl.webconnect_confirm
wait 2s
WebDriver_hdl.webdriver_windowsize
wait 2s
WebDriver_hdl.webdriver_click
wait 2s
WebDriver_hdl.drag_drop_confirm
wait 2s
WebDriver_hdl.moveto_confirm
wait 2s
WebDriver_hdl.webdisconnect_confirm
wait 2s
//SUTとの接続を切断---------------
Try
	connect_hdl.Disconnect_Sut "Windows3(RDP)"
	result_hdl.Result_Pass "DisconnectコマンドでSUTと切断する","PC"
Catch theException
	result_hdl.Result_Fail "DisconnectコマンドでSUTと切断する","PC"
End try
wait 2
//exitコマンド
Exit_hdl.exit_repeat
wait 2s
//logerror test
Try
	log_hdl.Log_Error "LogErrorテスト"
	result_hdl.Result_Pass "LogErrorコマンドでログが出力されること","PC"
	wait 2s
	Exit_hdl.Exit_All
End try



